### GET request to example server
POST http://localhost:7001/lollipop/register
Content-Type: application/json

{
  "name": "Joseph",
  "age": 12,
  "height": 6.3,
  "hobbies": [
    "Volleyball",
    "videogames"
  ],
  "description": "just a kind guy"
}

###