// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/lollipop.proto

package lollipop

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идендификатор пользователя
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Имя
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Возраст
	Age int64 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// Рост
	Height float32 `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	// Хобби
	Hobbies []string `protobuf:"bytes,5,rep,name=hobbies,proto3" json:"hobbies,omitempty"`
	// Описание
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Почта
	Email         string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_lollipop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_lollipop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_lollipop_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *User) GetHobbies() []string {
	if x != nil {
		return x.Hobbies
	}
	return nil
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserByIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор пользователя
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_api_lollipop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lollipop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_lollipop_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserByIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Пользователь
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_api_lollipop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lollipop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_lollipop_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идендификатор обновляемого пользователя
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Имя
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Возраст
	Age int64 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// Рост
	Height float32 `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	// Хобби
	Hobbies []string `protobuf:"bytes,5,rep,name=hobbies,proto3" json:"hobbies,omitempty"`
	// Описание
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Почта
	Email         string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_lollipop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lollipop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_lollipop_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserRequest) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UpdateUserRequest) GetHobbies() []string {
	if x != nil {
		return x.Hobbies
	}
	return nil
}

func (x *UpdateUserRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Возраст
	Age int64 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// Почта
	Email string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	// Рост
	Height float32 `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	// Хобби
	Hobbies []string `protobuf:"bytes,5,rep,name=hobbies,proto3" json:"hobbies,omitempty"`
	// Описание
	Description   string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_api_lollipop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lollipop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_api_lollipop_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RegisterUserRequest) GetHobbies() []string {
	if x != nil {
		return x.Hobbies
	}
	return nil
}

func (x *RegisterUserRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор пользователя который вернется после создания
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_api_lollipop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lollipop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_api_lollipop_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор пользоваетля
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_lollipop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lollipop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_lollipop_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_api_lollipop_proto protoreflect.FileDescriptor

const file_api_lollipop_proto_rawDesc = "" +
	"\n" +
	"\x12api/lollipop.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb0\x01\n" +
	"\x04User\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x03R\x03age\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\x12\x1d\n" +
	"\ahobbies\x18\x05 \x03(\tB\x03\xe0A\x01R\ahobbies\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\"$\n" +
	"\x12GetUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"0\n" +
	"\x13GetUserByIDResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"\xbd\x01\n" +
	"\x11UpdateUserRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x03R\x03age\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\x12\x1d\n" +
	"\ahobbies\x18\x05 \x03(\tB\x03\xe0A\x01R\ahobbies\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\"\xc3\x01\n" +
	"\x13RegisterUserRequest\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12\x15\n" +
	"\x03age\x18\x03 \x01(\x03B\x03\xe0A\x02R\x03age\x12\x19\n" +
	"\x05email\x18\a \x01(\tB\x03\xe0A\x02R\x05email\x12\x1b\n" +
	"\x06height\x18\x04 \x01(\x02B\x03\xe0A\x01R\x06height\x12\x1d\n" +
	"\ahobbies\x18\x05 \x03(\tB\x03\xe0A\x01R\ahobbies\x12%\n" +
	"\vdescription\x18\x06 \x01(\tB\x03\xe0A\x01R\vdescription\"/\n" +
	"\x14RegisterUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId2\xd7\x02\n" +
	"\bLollipop\x12R\n" +
	"\vGetUserById\x12\x13.GetUserByIDRequest\x1a\x14.GetUserByIDResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/lollipop/get\x12D\n" +
	"\n" +
	"UpdateUser\x12\x12.UpdateUserRequest\x1a\x05.User\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/lollipop/update\x12Z\n" +
	"\fRegisterUser\x12\x14.RegisterUserRequest\x1a\x15.RegisterUserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/lollipop/register\x12U\n" +
	"\n" +
	"DeleteUser\x12\x12.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/lollipop/deleteB-Z+github.com/VeeRomanoff/Lollipop/pb/lollipopb\x06proto3"

var (
	file_api_lollipop_proto_rawDescOnce sync.Once
	file_api_lollipop_proto_rawDescData []byte
)

func file_api_lollipop_proto_rawDescGZIP() []byte {
	file_api_lollipop_proto_rawDescOnce.Do(func() {
		file_api_lollipop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lollipop_proto_rawDesc), len(file_api_lollipop_proto_rawDesc)))
	})
	return file_api_lollipop_proto_rawDescData
}

var file_api_lollipop_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_lollipop_proto_goTypes = []any{
	(*User)(nil),                 // 0: User
	(*GetUserByIDRequest)(nil),   // 1: GetUserByIDRequest
	(*GetUserByIDResponse)(nil),  // 2: GetUserByIDResponse
	(*UpdateUserRequest)(nil),    // 3: UpdateUserRequest
	(*RegisterUserRequest)(nil),  // 4: RegisterUserRequest
	(*RegisterUserResponse)(nil), // 5: RegisterUserResponse
	(*DeleteUserRequest)(nil),    // 6: DeleteUserRequest
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_api_lollipop_proto_depIdxs = []int32{
	0, // 0: GetUserByIDResponse.user:type_name -> User
	1, // 1: Lollipop.GetUserById:input_type -> GetUserByIDRequest
	3, // 2: Lollipop.UpdateUser:input_type -> UpdateUserRequest
	4, // 3: Lollipop.RegisterUser:input_type -> RegisterUserRequest
	6, // 4: Lollipop.DeleteUser:input_type -> DeleteUserRequest
	2, // 5: Lollipop.GetUserById:output_type -> GetUserByIDResponse
	0, // 6: Lollipop.UpdateUser:output_type -> User
	5, // 7: Lollipop.RegisterUser:output_type -> RegisterUserResponse
	7, // 8: Lollipop.DeleteUser:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_lollipop_proto_init() }
func file_api_lollipop_proto_init() {
	if File_api_lollipop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lollipop_proto_rawDesc), len(file_api_lollipop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lollipop_proto_goTypes,
		DependencyIndexes: file_api_lollipop_proto_depIdxs,
		MessageInfos:      file_api_lollipop_proto_msgTypes,
	}.Build()
	File_api_lollipop_proto = out.File
	file_api_lollipop_proto_goTypes = nil
	file_api_lollipop_proto_depIdxs = nil
}
